# Generated by Django 3.2 on 2021-06-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210606_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.PositiveBigIntegerField(blank=True, default=0, editable=False),
        ),
    ]
